### ISSUE TITLE
WTP Menu broken

### ISSUE THREAD

**Issue by brianx87** [Omni-guides/Wabbajack-Modlist-Linux#14]
Had to re-image my deck and of course I forgot to back up my home folder, reinstalled WTP modlist and I've encountered issues I that had already fixed in previous installs but I can't find the information on fixing those issues.

First is that the menus are broken as seen below, I remember discussing something about this before along with a fix for improperly scaled Power Armour HUD/Overlay bu can't remember the fix.

![20240317192648_1](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/assets/11686648/2b6793d5-503c-452a-9baa-a79961a37eac)

Another issue was the mouse cursor on the map, you need to change a resolution setting for the map in one of the ini files, if you know how that fix is implemented?

**Comment by Omni-guides** [comment]
I think both are related to Resolution and Full Screen settings. 

You could try setting those things in both High FPS Physics Fix - WTP Settings mod, and also the fallout4prefs.ini file as well.

See if that fixes the menu being off-screen, and it may also fix the mouse cursor in the map, but if not we will deal with that after.

**Comment by brianx87** [comment]
Partially fixed, I can fix the menus in desktop mode running the game in a window, fullscreen completely disabled in both files, borderless only enabled in the WTP ini, the menus are working but the game runs in a window and the menu's break again in gaming mode with these settings. Tried different combinations of enabling and disabling fullscreen and borderless with no luck.

**Comment by Omni-guides** [comment]
I believe I have Fullscreen enabled, Borderless disabled and the resolution set to 1280x800 in both locations.

You may have to perform a Rootbuilder clear after editing the resolution in these places, so that it updates the prefs file that Rootbuilder copies to the Vanilla Game dir when you click play. Hopefully that will be enough, but you may have to get into deleting the Rootbuilder backup as well, forcing it to rebuild completely. 

I wish all modlists just used a Stock Game/Game Root, as it keeps things nicely packaged, but with the above set, I have the right resolution and the menu items are aligned.

Let me know how it goes.

**Comment by Omni-guides** [comment]
Closing due to lack of response. Feel free to get back in touch if you still need assistance.
