### ISSUE TITLE
ModOrganizer Error on Steam Deck

### ISSUE THREAD

**Issue by OldGameDad** [Omni-guides/Wabbajack-Modlist-Linux#18]
When I launch Fallout New Vegas as in step 7 I get the following error, attached. I have restarted and tried everything, even reaching out to the Mod Organizer 2 discord but got no response.

At this time, it seems that the install may be missing a step to account for this potential issue.
![app error](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/assets/123981054/ef111637-0e04-4f89-92f1-1266516dc299)

**Comment by OldGameDad** [comment]
In Step 5 about generating a clean prefix, you MUST follow the steps and do what it says.

I have resolved the issue and please update the guide.

Thank you.

**Comment by Omni-guides** [comment]
I did not need to clean the prefix, because it was already a brand new prefix as part of the new, clean New Vegas install.

You also didn't mention which guide you were following, there are two for Fallout New Vegas modlists. I will make a note on each guide to accept the clean prefix if there are problems later on.
