### ISSUE TITLE
Begin Again Steam Deck install does not launch

### ISSUE THREAD

**Issue by OldGameDad** [Omni-guides/Wabbajack-Modlist-Linux#19]
I have tried to do a fresh install, following the steps laid out exactly 3 times. I then did 2 attempts with using proton 8 and a fresh prefix. I then deleted everything and ensured it was completely clean installation and following the steps for the Begin Again install, and once I try to launch the game from MO2 for step 9, once you choose the Begin Again launching, and then the ini file option shows up, then a black screen, then it quits. The game quits on startup. I have gotten this result a few times, but MO2 throws no error or warning.

I am unsure what is going wrong, and since there's no error, the steps are incorrect or outdated, or incomplete.

I'll be completely honest, I'm at the point of paying someone to do the install for me, I have spent around 20 hours of work to correct any issues or errors, but I have exhausted my knowledge here.

**Comment by Omni-guides** [comment]
Apologies for the delay in response, I am currently on vacation. When I get home I will wipe my FNV and Begin Again set up, redownload and test the steps still work for me. 

Unfortunately FNV Wabbajack lists are far more troublesome than Skyrim or Fallout 4.

I will let you know my results when I have them.

**Comment by Lugoj** [comment]
I was having the same issue, it turned out that if you go to properties, compatibility and stop forcing compatibility (uncheck the box) this problem will go away. 
This is mentioned in the post install instructions of MO2 : https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md

**Comment by Omni-guides** [comment]
Thanks for following up - I'm finally getting more time to come back around to this so I will shortly be checking that the guide still works and makes sense, and will incorporate this as a step (or optional step if I can still get things working without it). I will keep this GitHub issue open until we have a working, repeatable solution.

**Comment by Lugoj** [comment]
I just followed your guide yesterday and it worked flawlessly.
I'd suggest you to just add the bit that we shouldn't force proton 8 compatibility as the MO2 installer asks us to do and instead not change anything (as stated in their own post install instructions that I linked above, as counter intuitive as it may sound).
Maybe your guide is linking an older version of MO2?

**Comment by Omni-guides** [comment]
Currently I had suggested to use Proton Experimental (Which is Proton 9.x), but I will double check once I have the latest Capital Punishment (just finishing off the WJ install now).

The version of MO2 is pulled in by RB's MO2 install script, so I would think it's close to the latest at the very least, but will also check.

**Comment by Omni-guides** [comment]
@OldGameDad Apologies for the delay with this, working on many other guides has meant I've only had time to revisit this now.

I actually have a new method for getting FNV lists to run, that avoids needing to copy and paste folder contents etc - it uses SteamTinkerLaunch instead of RockerBacon's MO2 install script. Currently, I've only re-written the guide for Capital Punishment, but will also be doing Begin Again with this method as soon as I have time.

If you still have a desire to get this running, then you could try following the steps detailed in the [Capital Punishment guide](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/wiki/Fallout-NV:-Capital-Punishment), replacing what is needed for Begin Again. Otherwise, I'll have a renewed Begin Again guide up as soon as I can. I'm going to close this Issue for now, but if you still have problems with the new method, then it may be best to join the Wabbajack Discord and I can help you there.
