### ISSUE TITLE
“Click to download […]” shows a blank screen

### ISSUE THREAD

**Issue by Nick1296** [Omni-guides/Wabbajack-Modlist-Linux#24]
I just want to report a small issue I found, since that other people may find this troubleshooting useful:

I installed wabbajack with [the bottles guide](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/wiki/Wabbajack-on-Steam-Deck-Linux-via-Bottles) and I noticed that when downloading a mod list the webview window where you had to click “slow download” would always be blank.

My solution was to install `xact xact_x64 d3dcompiler_47 d3dx11_43 d3dcompiler_43 vcrun2022 dotnet6 dotnet7` from the bottles dependencies, but the issue as persisting, so I also installed the webview evergreen bootstrapper without fixing the issue.

What resolved the issue in the end was to enable the virtual desktop option in the bottle settings (to be precise, in settings→ advanced display settings), but it worked only temporarily.

Moving the renderer back to GL (the default option) may also help with this problem.

I will keep testing what is the stabler method to resolve the issue, but I think this might be related to my wine version (I am using wine-tkg 9.20)

Thanks for this collection of guides!

**Comment by Omni-guides** [comment]
> My solution was to install `xact xact_x64 d3dcompiler_47 d3dx11_43 d3dcompiler_43 vcrun2022 dotnet6 dotnet7` from the bottles dependencies, but the issue as persisting, so I also installed the webview evergreen bootstrapper without fixing the issue.

These shouldn't be needed for Wabbajack, but are needed for the games themselves, depending on the features and mods the modlists contains.

You may indeed get better stability with gl than vulkan on your system - I'm not sure of the exact balance of hardware and renderer - perhaps full AMD GPUs benefit from gl, NVidia from vulkan, for example. The bottles guide I was really aiming at Steam Deck use, because on a full desktop base wine is usually a better option (one less layer/application to go through if not using bottles). Base wine isn't an option on SteamOS, hence the use of bottles.

**Comment by Nick1296** [comment]
I see, I just used bottles since it looked way easier to setup than
fiddling manually with wine prefixes.

I'll see if I have other problems and in case reinstall only with wine,
thanks!
Mattia Nicolella

**Comment by Omni-guides** [comment]
I have plans that may help :) I'm about 50% done on a bash script that should automate the Wine version for Linux systems (not using the default wine prefix), and I've started reading up on bottles-cli to see if there's a way I can automate the creation of a working bottles environment.

They are not ready yet, but my aim is to work towards that.

**Comment by Omni-guides** [comment]
How did you get on?

**Comment by Nick1296** [comment]
I reinstalled everything with wine and I feel it works more or less the same, the only changesl I needed to fix the black screen is leaving the default renderer.

I also noticed that with wine on Wayland (plasma6/hyprland) there's an empty window (transparent on plasma6/black on hyprland) which is always in the top layer and in plasma6 cannot be moved.

But these are minor things, I am downloading a modpack at the moment, so I'll follow up if some other things happen

**Comment by Omni-guides** [comment]
How did you get on?

**Comment by Nick1296** [comment]
Sorry for the late reply,

I managed to install a [Lost Legacy](https://github.com/Lost-Outpost/lost-legacy) though wabbajack without any major problems. I also followed parts of your guide for the Anvil modpack (specifically your one liner script to install wine dependencies) and I also manually installed the dotnet5 console and desktop runtime, though the manual method you mentioned, since it was required by the modpack.

After doing this the game starts, but it hangs before it is able to load the main menu.

any suggestions are appreciated! I will follow-up once again when I manage to resolve this issue.

**Comment by Omni-guides** [comment]
Some modlists - specifically those that use Skyrim 1.5.97 and the .Net Script Framework, will also need dotnet4.X installed - I see this 'hang before menu options' issue fairly regularly because of this.

Now depending on your system, you may only be able to install dotnet4.0, or 4.2, some systems (distro+hardware) seem fine with dotnet4.8.. It's a real mess. Thankfully, any version of dotnet4.X appears to make this work. In my auto install script, if it detects the modlist as one of the few I have specific additions for, then it will install 4.0 - unfortunately I haven't included Lost Legacy in that section just yet.

A word of caution though, installing this with protontricks will likely set the wine environment to WinXP to complete the dotnet4 installation, so you may have to switch this back to win10 (for your Lost Legacy entry in Steam).

**Comment by Nick1296** [comment]
You were right, installing dotnet 4.x is a real pain.

I managed to install it with GE-proton 9.18 and I had to set the wine environment back to win10 (installation sets it to win7).

Now the game starts properly and I am ableto play.
The only issue is that areas in open world have terrible performance and a lot of stutter. At this point I don't know if I have to blame the Enb or wine. Do you have any suggestions?

**Comment by Omni-guides** [comment]
Entirely depends on your specs compared to what the modlist suggests. Usually performance isn't that different between the two, though vRAM usage can be higher via Proton for whatever reason.

Does disabling ENB temporarily improve performance?

**Comment by Omni-guides** [comment]
No response, so closing this for now.

**Comment by Nick1296** [comment]
Sorry for the long time to reply.

 I can confirm that the problems I am having currently are due to the modpack just being too heavy (even though I have 32GB of RAM, a ryzen9 and a 3080 mobile).
 I am currently playing with the setting to find the combination that allows my machine to run smoothly.

**Comment by romanovzky** [comment]
Gosh, thank you both for this! Indeed it needed dotnet 4.X, I was going mad...
