### ISSUE TITLE
No "Stock Game" folder

### ISSUE THREAD

**Issue by mdorier** [Omni-guides/Wabbajack-Modlist-Linux#9]
I'm following the tutorial to install Legends Of The Frost on my Steam Deck, [here](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/wiki/Skyrim:-Legends-of-the-Frost). I reached the point where I need to select the "Stock Game" folder (`/home/deck/Games/Skyrim/LegendsOfTheFrost/LegendsOfTheFrost-WJ/Stock Game/`), but there is no such folder. Am I supposed to copy it from somewhere? Were I supposed to do something else on Windows besides asking Wabbajack to download/install the modlist?

**Comment by Omni-guides** [comment]
Hey! It's likely that a newer version of LotF has stopped using the Stock Game method, and probably moved to Rootbuilder with Vanilla Game dir.

I'll update LotF and update the guide once confirmed.

In the mean time, you can likely look at the other guides -  e.g Sonvgarde, Septimus - for how to handle the process without Stock Game. The process should be largely the same, except for needing to enable visibility of dot files, and pointing MO2 to the Vanilla Game dir. That's covered in those guides, but jump into the WJ discord if you get stuck and we can talk through it.

**Comment by mdorier** [comment]
Thanks. I followed the Sonvgarde tutorial, adapted for LOTF. I didn't do the "Step 7 - Install VCREDIST2022" (this step isn't in the LOTF tutorial, I assume it's not necessary?). I also didn't do "Step 7 Disable ENB" from the LOTF tutorial as it refers to the "Stock Game" folder again and if I look at the "Step 5 - Disable ENB" from the Sonvgarde tutorial, it refers to an "ENBSERIES" that just isn't present for LOTF.

Now in MO2 when I select Legends of the Frost and click Run, the game starts full-screen and for a brief instant I see the Bethesda logo and hear the drums, and there is a "compiling shaders" on the top-left of the screen, showing shaders being compiled. But then it just stops and goes back to MO2.

Any idea what the problem can be?

**Comment by Omni-guides** [comment]
Yeah, much as you mention - you need to follow the steps to disable ENB - I haven't had a chance to check yet, but it sounds like as well as moving from Stock Game to Rootbuilder, the latest version of LotF also now includes an ENB. Sadly, these can be called whatever the mod author wants, but usually at least includes 'ENB' letters in the name. After unticking them, run a Rootbuilder clear as per the Sovngarde guide and hopefully that will be that. If there really isn't any ENB preset in LotF, then sadly I'll have to check what it is using that is compiling shaders (maybe Community Shaders?).

If you don't see a pop up when you click play complaining that certain .dll's can't be loaded, then you likely don't need VCREDIST2022 (again I'll have to confirm when I try it myself). There is a small chance that because the game launched (and crashed) with ENB enabled, that you may get into a situation with ENB and Rootbuilder fighting, but we'll cross that bridge if/when we get to it.

**Comment by Omni-guides** [comment]
I had some time to download the latest LotF and try it out - there is no included ENB, so nothing to worry about there. I also didn't need to install VCREDIST2022.

However, I did see that the list now includes Community Shaders (with optional ReShade), and this is likely where you are seeing the crash while it is compiling shaders. So far that you will either have to disable Community Shaders (I presume at this stage just by unticking the "Community Shaders entry in MO2"), or install d3dcompiler_47 inside the prefix. You could grab the command from [Step 6](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/wiki/Skyrim:-Sovngarde#step-6---install-required-wine-additions) of the Sovngarde guide in the mean time, until I get time to fully update the LotF guide. Just remember to change 'Sovngarde' in the command to match whatever you called the Steam entry for your Legends of the Frost non-steam game.

I'll hopefully get a change to refresh the LotF guide to reflect these changes to the list requirements.

**Comment by mdorier** [comment]
Unfortunately neither seem to work. I try unticking all the boxes under the "Community Shaders" category, then did Rootbuild > Clear. The game still crashes after a second, the only difference is that I don't see "compiling shaders" anymore at the top. I also try just unticking the "Community Shaders" entry (not the full category), no luck either.

I did Step 6 of the Sovngarde guide (I had already done it but just to be sure), changing "Skyrim - Sovngarde" into "Skyrim - Legends of the Frost" (name of my entry), but no difference.

Did you manage to run LotF? If not, is there anything I can provide (logs, etc.) that could help?

**Comment by Omni-guides** [comment]
Odd. It seems to run fine for me, with Community Shaders still enabled. - at least until I go through the cart ride and initial dragon attack etc (i'd forgotten how long that drags on :D ) - No crashes or issues as far as I can tell.

I didn't do anything specific either, just basically the steps from the Sovngarde guide, skipping the parts about disabling ENB. Everything else was the same. Looking back at my command history, I actually did install VCREDIST2022 - though perhaps just out of habit rather than requirement. Might be worth installing it anyway, it's small and won't cause issues, though may not fix them either.

The list does include Crashlogger, so there will be a crash log detailing what caused the crash, but not necessarily how to fix it - the logs are a bit hard to find as they are technically on the 'Windows' side of wine. You'll need to know the APPID of your Steam entry for Legends of the Frost. You can get that with:

```
protontricks -l | grep -i Legends
```

It'll return something like:

```
bash-5.2$ protontricks -l | grep -i Legends
Non-Steam shortcut: Skyrim - Legends of the Frost (3416644177)
```

Then you can use the number there to get to the logs

``` 
cd /home/deck/.local/share/Steam/steamapps/compatdata/3416644177/pfx/drive_c/users/steamuser/My\ Documents/My\ Games/Skyrim\ Special\ Edition/SKSE/
```

Just replace 3416644177 with your own APPID from the first command. Inside that directory, will be a file with a timestamp in the filename, e.g. crash-2023-08-28-14-16-55.log

As an example, the top part is of most interest, in the 'Probable Call stack', for example

```Skyrim SSE v1.6.640
CrashLoggerSSE v1-8-0-0 Feb  1 2023 00:20:05

Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x000140F322A1 SkyrimSE.exe+0F322A1 mov rcx, [rcx+0x58]

SYSTEM SPECS:
        OS: Microsoft Windows 10 Pro v10.0.19043
        CPU: GenuineIntel Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
        GPU #1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
        PHYSICAL MEMORY: 10.73 GB/31.17 GB

PROBABLE CALL STACK:
        [ 0] 0x000140F322A1 SkyrimSE.exe+0F322A1 -> 82665+0x11  GFxMovieView::InvokeNoReturn
        [ 1] 0x000140F30FEA SkyrimSE.exe+0F30FEA -> 82640+0xEA  GFxMovieView::sub
        [ 2] 0x000140935F61 SkyrimSE.exe+0935F61 -> 53315+0x361 JournalMenu::sub
        [ 3] 0x000140F17D8D SkyrimSE.exe+0F17D8D -> 82082+0x6BD
        [ 4] 0x000140678599 SkyrimSE.exe+0678599 -> 39042+0x19  Job_UI
        [ 5] 0x000140C6C628 SkyrimSE.exe+0C6C628 -> 69378+0xD8
        [ 6] 0x000140C6CBF1 SkyrimSE.exe+0C6CBF1 -> 69380+0x361
        [ 7] 0x000140C6AF7A SkyrimSE.exe+0C6AF7A -> 69344+0x8A
        [ 8] 0x000140C45E4D SkyrimSE.exe+0C45E4D -> 68445+0x3D  StartAddress_0
        [ 9] 0x00007B61469D kernel32.dll+001469D
        [10] 0x00017000F1A7    ntdll.dll+000F1A7
```

**Comment by mdorier** [comment]
I wiped out my installation (of LOTF, not Skyrim) and started over, following the Sovngarde guide, but no luck.

Just to be sure: at the end of Step 4, when clicking on the cogs, I have to then add (+) an entry for Legends of the Frost, right? Does its place in the list matter? Do I have to fill anything else apart from the Binary path? (by default only "force load libraries" is ticked).

I'm attaching the crash log, if it's useful. Tomorrow I will try to also completely uninstall and reinstall Skyrim. It's always possible that some dll or executable conflicts from a previous installation of MO2 (I had initially followed a tutorial online that didn't use WJ).

[crash-2023-08-28-19-54-36.log](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/files/12457898/crash-2023-08-28-19-54-36.log)

**Comment by Omni-guides** [comment]
No, you should just edit the "Skyrim Script Extender" entry already present in the Cog Executables, and it should point to skse64_loader.exe in the vanilla game directory - this file may not actually exist, but just use that path anyway, as Rootbuilder will copy the executable into the right place on launch.

The crashlog is odd, in that it just lists that Skyrim itself is crashing, without a cause.

Which proton version have you set in Steam? Silly question, but does vanilla Skyrim load and start ok?

I'll try and get enough time tomorrow to update the LotF guide with the steps I took, it's odd that you're having such issues. If you want to go through it together 'live' then drop by the Discord channel and we can work through it until you're up and running :)

**Comment by mdorier** [comment]
Ok I reinstalled Skyrim and it works, now. I noticed that after uninstalling I still had some files in Skyrim's folder, including skse64_loader.exe among others, so I removed them. I guess those files were from me previously following a tutorial in which some files needed to be put in the game's folder (probably).

The only thing I had to do differently from Sovngarde was the step for the missing audio, which isn't in the Sovngarde guide, but apart from that everything seems to be working fine.

Thanks for your help! I'll close the issue.
